# Site settings
title: Something Awesome
email: nico@delightfuldev.com
description: > # this means to ignore newlines until "baseurl:"
  Hopefuly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicnocquee.com" # the base hostname & protocol for your site
twitter_username: nicnocquee
github_username:  nicnocquee

# Build settings
markdown: kramdown
gem: [octopress-codeblock,octopress-codefence,octopress-image-tag,octopress-quote-tag,octopress-solarized,octopress-social,octopress-linkblog,octopress-filter-tag,octopress-filters,octopress-comment-tag,jekyll-sitemap]